channels:
  - defaults
dependencies:
  - numpy>=1.20
  - pip>=20.3.3
  - python=3.9
  - pip:
      - matplotlib==3.4.3
      - reproject==0.8
      - astropy==4.3.1
      - batman-package==2.4.8
      - lightkurve>=2.0.0